# Generated by Django 3.0.4 on 2020-03-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_february_january'),
    ]

    operations = [
        migrations.DeleteModel(
            name='February',
        ),
        migrations.DeleteModel(
            name='January',
        ),
    ]
