# Generated by Django 3.0.4 on 2020-03-27 17:48

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0005_february_january'),
    ]

    operations = [
        migrations.CreateModel(
            name='April',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('plates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='August',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('plates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='December',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('plates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='July',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('plates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='June',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('plates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='March',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('plates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='May',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('plates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='November',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('plates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='October',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('plates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='September',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('plates', models.IntegerField()),
            ],
        ),
    ]
