# Generated by Django 3.0.4 on 2020-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0006_april_august_december_july_june_march_may_november_october_september'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('afternoon', models.CharField(max_length=100)),
                ('night', models.CharField(max_length=100)),
            ],
        ),
    ]
