# Generated by Django 3.0.4 on 2020-04-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0007_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAbsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlatePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
