# Generated by Django 3.0.4 on 2020-04-01 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0008_dailyabsent_plateprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyabsent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
