# Generated by Django 3.0.4 on 2020-04-02 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0009_dailyabsent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyabsent',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_number', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=100)),
                ('mob_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Mobile number', max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
