# Generated by Django 3.0.4 on 2020-04-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0010_auto_20200402_0652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyAbsent',
        ),
    ]
