# Generated by Django 3.0.4 on 2020-04-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0011_delete_dailyabsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mess_number',
            field=models.IntegerField(blank=True),
        ),
    ]
