# Generated by Django 3.0.4 on 2020-04-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0012_auto_20200402_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mess_number',
            field=models.IntegerField(null=True),
        ),
    ]
